"use client"
import { Inter } from 'next/font/google'
import GlobalStyle from '../globalStyles'
import { theme } from "../theme.ts"
import { ThemeProvider } from 'styled-components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type IRootLayout = {
  children: React.ReactNode
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <body className={inter.className}>{children}</body>
      </ThemeProvider>
    </html>
  )
}
