"use client"
import { Inter } from 'next/font/google'
import GlobalStyle from '../globalStyles'
import { theme } from "../theme.ts"
import styled, { ThemeProvider } from 'styled-components'

import { Sidebar } from "../Components/Sidebar"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type IRootLayout = {
  children: React.ReactNode
}

const SMainContainer = styled.body`
  padding: 12px;
  display: flex;
  justify-content: flex-start;
  gap: 12px;
`

export default function RootLayout({ children }: IRootLayout) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <GlobalStyle />
        <SMainContainer className={inter.className}>
          <Sidebar />
          <div className="page">
            {children}
          </div>
        </SMainContainer>
      </ThemeProvider>
    </html>
  )
}
